version: '3.1'

services:
  db:
    image: postgres
    container_name: webol_dev_postgres
    restart: no
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=webol

    ports:
      - "5432:5432"
