name: check

on: [ pull_request, workflow_dispatch ]

env:
 SCCACHE_GHA_ENABLED: "true"
 RUSTC_WRAPPER: "sccache"
 CARGO_TERM_COLOR: always

jobs:
 check:
   runs-on: ubuntu-latest
   steps:
     - name: Run sccache-cache
       uses: mozilla-actions/sccache-action@v0.0.4

     - uses: actions/checkout@v4

     - run: cargo check
     - run: cargo clippy

 check-release:
   runs-on: ubuntu-latest
   steps:
     - name: Run sccache-cache
       uses: mozilla-actions/sccache-action@v0.0.4

     - uses: actions/checkout@v4

     - run: cargo check --release
     - run: cargo clippy --release
