name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  SQLX_OFFLINE: "true"
  CARGO_TERM_COLOR: always
  CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER: arm-linux-gnueabihf-gcc

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3

      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: armv7-unknown-linux-gnueabihf
          components: rustfmt, clippy
          override: true

      - name: Install arm linker
        run: sudo apt update && sudo apt install gcc-arm-linux-gnueabihf -y

      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target armv7-unknown-linux-gnueabihf

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/fxqnlr/webol:dev-latest
            ghcr.io/fxqnlr/webol:dev-${{ github.run_number }}